// 紙貨行的貨架 —— 每一項都對應 public/img 裡的一張照片
export const products = [
  {
    slug: "brass-fountain-pen",
    name: "黃銅鋼筆．日用款",
    tagline: "越寫越順手的那種重量",
    price: 2480,
    category: "筆",
    image: "/img/pen1.jpg",
    stock: "現貨 6",
    note: "筆身車過就不再上漆，讓黃銅自己長出手澤。附上 EF、F 兩種筆尖，出廠前每支都試寫過一行字。",
    specs: [
      ["材質", "實心黃銅 / 不鏽鋼筆尖"],
      ["重量", "31 g（含筆蓋）"],
      ["上墨", "卡式墨水管 + 吸墨器"],
      ["產地", "台灣組裝"],
    ],
  },
  {
    slug: "thread-bound-notebook",
    name: "線裝筆記本",
    tagline: "攤得平，寫到最後一頁都不打架",
    price: 320,
    category: "紙品",
    image: "/img/note2.jpg",
    stock: "現貨 24",
    note: "裸背手工穿線，翻開會乖乖躺平。內頁是米色的 100 磅道林紙，鋼筆吃墨也不透。",
    specs: [
      ["尺寸", "A5 / 21 × 14.8 cm"],
      ["頁數", "192 頁 / 5 mm 方格"],
      ["裝訂", "手工穿線裸背"],
      ["紙張", "米白道林 100 gsm"],
    ],
  },
  {
    slug: "desktop-pencil-sharpener",
    name: "桌上型削鉛筆機",
    tagline: "轉起來會上癮的金屬手感",
    price: 1680,
    category: "桌上",
    image: "/img/pencil3.jpg",
    stock: "現貨 4",
    note: "老工廠留下來的鑄件模具，補上新的雙刀輪。夾得住六角桿也夾得住圓桿，木屑集屑盒抽出來倒就好。",
    specs: [
      ["本體", "鑄鐵烤漆"],
      ["刀輪", "螺旋雙刀 / 可換"],
      ["適用", "7 – 11.5 mm 筆桿"],
      ["重量", "760 g"],
    ],
  },
  {
    slug: "washi-tape-set",
    name: "和紙膠帶．基本三卷",
    tagline: "撕得順、不留痕、可以寫字",
    price: 240,
    category: "貼物",
    image: "/img/washi4.jpg",
    stock: "現貨 40",
    note: "選了三個最耐看的顏色：牛皮、灰藍、磚紅。貼在紙上像本來就印好的一樣。",
    specs: [
      ["寬度", "15 mm × 3 卷"],
      ["長度", "每卷 8 m"],
      ["材質", "日本和紙 / 水性膠"],
      ["特性", "可手撕、可覆寫"],
    ],
  },
  {
    slug: "mini-stapler",
    name: "口袋釘書機",
    tagline: "小歸小，一次能咬十張",
    price: 380,
    category: "桌上",
    image: "/img/staple5.jpg",
    stock: "現貨 18",
    note: "掌心大小的全金屬機身，彈簧回彈很扎實。用 10 號針，補充針各文具店都有。",
    specs: [
      ["針號", "10 號"],
      ["裝訂", "一次 2 – 12 張"],
      ["機身", "鋅合金"],
      ["顏色", "霧黑 / 米白 / 軍綠"],
    ],
  },
  {
    slug: "brass-ruler",
    name: "黃銅直尺 15 cm",
    tagline: "壓紙、裁線、當書籤都行",
    price: 460,
    category: "桌上",
    image: "/img/ruler6.jpg",
    stock: "現貨 12",
    note: "蝕刻的刻度不會磨掉，邊緣導了角不刮手。用久了會變深金色，是它該有的樣子。",
    specs: [
      ["長度", "150 mm"],
      ["刻度", "正面 mm / 背面 inch"],
      ["厚度", "2 mm"],
      ["材質", "H62 黃銅蝕刻"],
    ],
  },
  {
    slug: "glass-bottled-ink",
    name: "玻璃瓶裝鋼筆墨水",
    tagline: "夜讀藍、柿子橙、青苔綠",
    price: 560,
    category: "筆",
    image: "/img/ink7.jpg",
    stock: "現貨 9",
    note: "台灣小廠一次只調三十瓶。瓶底做了斜面，墨水剩不多也吸得起來。標籤是活版印的。",
    specs: [
      ["容量", "40 ml"],
      ["性質", "水性染料墨"],
      ["色號", "夜讀藍 / 柿子橙 / 青苔綠"],
      ["備註", "非防水，適合日常書寫"],
    ],
  },
  {
    slug: "sticky-note-pad",
    name: "便利貼本．方角",
    tagline: "方角比圓角好貼，我們試過",
    price: 150,
    category: "貼物",
    image: "/img/sticky8.jpg",
    stock: "現貨 55",
    note: "膠條加寬到 15 mm，貼在書頁翻很多次也不掉。顏色是低彩度的灰粉、灰黃、灰藍。",
    specs: [
      ["尺寸", "75 × 75 mm"],
      ["張數", "每本 100 張"],
      ["膠條", "15 mm 可再貼"],
      ["組合", "3 色 / 本"],
    ],
  },
  {
    slug: "weekly-planner",
    name: "週計畫手帳．無時效",
    tagline: "哪天開始都不算浪費",
    price: 540,
    category: "紙品",
    image: "/img/plan9.jpg",
    stock: "現貨 20",
    note: "跨頁左邊七天、右邊整頁空白格。沒有印日期，跳過一週也不會有空白的罪惡感。",
    specs: [
      ["尺寸", "18 × 25 cm"],
      ["內頁", "54 週 / 方格 + 空白"],
      ["封面", "細紋布膜"],
      ["裝訂", "膠裝可攤平"],
    ],
  },
  {
    slug: "leather-journal",
    name: "植鞣皮筆記本套",
    tagline: "會跟著你一起變舊",
    price: 1280,
    category: "紙品",
    image: "/img/journal10.jpg",
    stock: "現貨 7",
    note: "義大利植鞣皮，用鬆緊帶換內冊。剛拿到偏淺，曬過幾次太陽、放進包裡磨一磨就對了。",
    specs: [
      ["尺寸", "A5 可用"],
      ["皮革", "植鞣牛皮 2 mm"],
      ["內冊", "附方格內冊 1 本"],
      ["補充", "可換 A5 標準內冊"],
    ],
  },
  {
    slug: "dual-tip-marker",
    name: "水性雙頭簽字筆",
    tagline: "一頭寫字，一頭塗塊面",
    price: 90,
    category: "筆",
    image: "/img/marker11.jpg",
    stock: "現貨 60",
    note: "細字 0.4 mm、粗頭是斜切軟毛。水性、無味，蓋回去放半年還是出得了水。",
    specs: [
      ["筆頭", "0.4 mm / 斜切軟毛"],
      ["墨水", "水性顏料"],
      ["顏色", "12 色可單買"],
      ["特性", "低氣味 / 不易透背"],
    ],
  },
  {
    slug: "soft-highlighter",
    name: "柔色螢光筆",
    tagline: "劃了還看得清楚字",
    price: 75,
    category: "筆",
    image: "/img/hl12.jpg",
    stock: "現貨 48",
    note: "刻意調低螢光度，影印起來不會變一片黑。五個顏色都是加了灰的粉調。",
    specs: [
      ["筆頭", "斜切 4 mm"],
      ["墨水", "低彩度水性"],
      ["顏色", "奶油 / 灰粉 / 霧綠 / 淺藍 / 藕"],
      ["組合", "5 入 / 單支"],
    ],
  },
  {
    slug: "paper-clip-jar",
    name: "造型迴紋針．玻璃罐裝",
    tagline: "散在抽屜裡也好看",
    price: 180,
    category: "桌上",
    image: "/img/clip13.jpg",
    stock: "現貨 30",
    note: "黃銅色與霧黑各半，形狀是老式的水滴。玻璃罐留著裝別的小東西剛好。",
    specs: [
      ["數量", "約 80 支 / 罐"],
      ["尺寸", "28 mm"],
      ["電鍍", "黃銅 / 霧黑"],
      ["容器", "軟木塞玻璃罐"],
    ],
  },
  {
    slug: "handmade-scissors",
    name: "手工事務剪刀",
    tagline: "剪紙的聲音很療癒",
    price: 720,
    category: "桌上",
    image: "/img/scissor14.jpg",
    stock: "現貨 10",
    note: "刀刃分開研磨再組起來，剪到刀尖都不會卡。握把包了一層消光漆，手汗多也不滑。",
    specs: [
      ["全長", "175 mm"],
      ["刀刃", "高碳不鏽鋼"],
      ["握把", "消光塗裝"],
      ["保養", "附小罐保養油"],
    ],
  },
  {
    slug: "dip-pen-nib-set",
    name: "沾水筆桿與筆尖組",
    tagline: "練字、畫線稿都從這支開始",
    price: 640,
    category: "筆",
    image: "/img/calli15.jpg",
    stock: "現貨 8",
    note: "櫸木筆桿加通用筆舌，配三種硬度的筆尖。附一頁我們自己整理的入門說明。",
    specs: [
      ["筆桿", "櫸木 / 通用筆舌"],
      ["筆尖", "G 尖 / 學生尖 / 圓體尖"],
      ["附件", "入門說明一頁"],
      ["建議墨", "搭配沾水筆墨或碳素墨"],
    ],
  },
  {
    slug: "wood-rubber-stamp",
    name: "木柄橡皮印章",
    tagline: "蓋一個就知道這頁是誰的",
    price: 300,
    category: "印章",
    image: "/img/stamp16.jpg",
    stock: "現貨 15",
    note: "現成圖樣有『閱』『已寄』『今天』『備份』四款，也可以留字讓我們刻。雷射雕刻，邊緣很利。",
    specs: [
      ["面徑", "30 mm"],
      ["柄", "山毛櫸原木"],
      ["圖樣", "四款現貨 / 可客製"],
      ["建議", "搭配油性印台"],
    ],
  },
  {
    slug: "desk-mat",
    name: "書桌墊．雙面",
    tagline: "寫字墊一下，字會好看一點",
    price: 880,
    category: "桌上",
    image: "/img/desk17.jpg",
    stock: "現貨 11",
    note: "一面織紋布、一面軟木。邊緣車了皮條收邊，捲起來用附的皮帶綁著帶走。",
    specs: [
      ["尺寸", "60 × 40 cm"],
      ["正面", "聚酯織紋"],
      ["背面", "天然軟木"],
      ["收邊", "植鞣皮條 + 束帶"],
    ],
  },
  {
    slug: "drafting-eraser",
    name: "製圖橡皮擦",
    tagline: "擦得乾淨，屑會結成條",
    price: 45,
    category: "桌上",
    image: "/img/eraser18.jpg",
    stock: "現貨 90",
    note: "日本老橡皮廠的配方，擦鉛筆不留油光。紙套上有刻痕，用短了折一段就好。",
    specs: [
      ["尺寸", "60 × 21 × 12 mm"],
      ["材質", "PVC-free 塑膠擦"],
      ["特性", "低粉塵 / 屑成條"],
      ["包裝", "可撕紙套"],
    ],
  },
  {
    slug: "colored-pencils-36",
    name: "色鉛筆 36 色．鐵盒",
    tagline: "顏色排起來就很想畫",
    price: 1120,
    category: "筆",
    image: "/img/color19.jpg",
    stock: "現貨 9",
    note: "油性芯，疊色不會糊。鐵盒做成兩層抽屜，鉛筆躺著放不會滾。色號印在筆桿尾端。",
    specs: [
      ["支數", "36 色"],
      ["筆芯", "3.3 mm 油性"],
      ["筆桿", "椴木六角"],
      ["盒", "雙層鐵盒"],
    ],
  },
  {
    slug: "letter-paper-set",
    name: "信紙信封組",
    tagline: "還是有些話想寫在紙上",
    price: 260,
    category: "紙品",
    image: "/img/letter20.jpg",
    stock: "現貨 26",
    note: "薄磅數的米色紙，對摺三折剛好進信封。信紙上淡淡印了橫線,寫直的也不歪。",
    specs: [
      ["信紙", "24 張 / A5 橫線"],
      ["信封", "12 個 / 西式"],
      ["紙色", "米白"],
      ["附贈", "封口貼紙一張"],
    ],
  },
];

export const PER_PAGE = 6;

export function getPage(page) {
  const total = Math.max(1, Math.ceil(products.length / PER_PAGE));
  const current = Math.min(Math.max(1, page || 1), total);
  const start = (current - 1) * PER_PAGE;
  return {
    current,
    total,
    items: products.slice(start, start + PER_PAGE),
    count: products.length,
  };
}

export function getProduct(slug) {
  return products.find((p) => p.slug === slug);
}

export function priceText(n) {
  return "NT$ " + n.toLocaleString("en-US");
}
